"""
digest_generator.py — Weekly performance digest generator.

Output formats:
  - Markdown (for Slack/email delivery, terminal display)
  - Structured dict (for frontend dashboard API)

Digest sections:
  1. Funnel Summary       — sent → replied → positive → interviews
  2. Top Performing Hooks — which personalization strategies worked
  3. Best Send Times      — hour-by-hour reply rate heatmap
  4. Subject Line Winners — highest-converting subjects with stats
  5. Company Patterns     — which company types respond
  6. Recommendations      — top 5 actions for next week
  7. Week-over-Week       — delta vs prior snapshot (if available)
"""

from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from .models import LearningSnapshot, OutreachMetrics, Recommendation, SuccessPattern

log = logging.getLogger(__name__)

_LEARNING_DB = Path("data/learning.db")

_BAR_WIDTH = 20   # chars for ASCII bar charts


class DigestGenerator:
    """
    Generates weekly digest from a LearningSnapshot.

    Usage:
        generator = DigestGenerator()
        md = generator.generate_markdown(snapshot)
        print(md)
    """

    def generate(self, snapshot: LearningSnapshot) -> LearningSnapshot:
        """Populate snapshot.digest_markdown and return the snapshot."""
        snapshot.digest_markdown = self.generate_markdown(snapshot)
        return snapshot

    # ── Markdown digest ────────────────────────────────────────────────────────

    def generate_markdown(self, snapshot: LearningSnapshot) -> str:
        m  = snapshot.metrics
        ps = snapshot.patterns
        rs = snapshot.recommendations

        lines = [
            f"# NEXUS Weekly Digest — {snapshot.snapshot_date}",
            "",
            "## Outreach Funnel",
            f"```",
            self._funnel_chart(m),
            f"```",
            "",
        ]

        # Funnel numbers
        lines += [
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Sent | {m.total_sent} |",
            f"| Delivered | {m.total_delivered} ({m.delivery_rate:.0%}) |",
            f"| Replied | {m.total_replied} ({m.reply_rate:.0%}) |",
            f"| Positive | {m.total_positive} ({m.positive_rate:.0%}) |",
            f"| Interviews | {m.total_interviews} ({m.interview_rate:.0%}) |",
            f"| Offers | {m.total_offers} |",
            "",
        ]

        # Hook performance
        if m.by_hook_type:
            lines += ["## Hook Performance", ""]
            rows = sorted(
                m.by_hook_type.items(),
                key=lambda kv: kv[1].reply_rate,
                reverse=True,
            )
            lines.append("| Hook Type | Sent | Reply Rate | vs Avg |")
            lines.append("|-----------|------|------------|--------|")
            for hook, stats in rows:
                delta = stats.reply_rate - m.reply_rate
                sign  = "+" if delta >= 0 else ""
                lines.append(
                    f"| {hook} | {stats.sent} | "
                    f"{stats.reply_rate:.0%} | "
                    f"{sign}{delta:.0%} |"
                )
            lines.append("")

        # Best send times
        if m.by_send_hour:
            lines += ["## Best Send Hours (UTC)", ""]
            sorted_hours = sorted(m.by_send_hour.items())
            lines.append("```")
            for hour, stats in sorted_hours:
                if stats.sent < 3:
                    continue
                bar = _bar(stats.reply_rate, max_val=0.5)
                lines.append(f"  {hour:02d}:00  {bar}  {stats.reply_rate:.0%} ({stats.sent} sends)")
            lines.append("```")
            lines.append("")

        # Top subjects
        if m.top_subjects:
            lines += ["## Top Converting Subjects", ""]
            for i, subj in enumerate(m.top_subjects[:5], 1):
                lines.append(f"{i}. `{subj}`")
            lines.append("")

        # Significant patterns
        sig = [p for p in ps if p.is_significant()]
        if sig:
            lines += ["## Discovered Patterns", ""]
            for p in sig[:8]:
                lines.append(f"- {p}")
            lines.append("")

        # Recommendations
        if rs:
            lines += ["## Recommendations for Next Week", ""]
            for i, r in enumerate(rs[:5], 1):
                lines.append(f"{i}. **{r.type.value}** — {r.action}")
                lines.append(f"   *Evidence: {r.evidence}*")
                lines.append(f"   *Estimated impact: +{r.impact_estimate:.1f}pp reply rate*")
                lines.append("")

        # Footer
        lines += [
            "---",
            f"*Generated by NEXUS FeedbackLoop at {snapshot.snapshot_date}*",
        ]

        return "\n".join(lines)

    # ── Structured dict (for dashboard API) ───────────────────────────────────

    def generate_dict(self, snapshot: LearningSnapshot) -> dict:
        m = snapshot.metrics
        return {
            "date":            snapshot.snapshot_date,
            "funnel": {
                "sent":       m.total_sent,
                "delivered":  m.total_delivered,
                "replied":    m.total_replied,
                "positive":   m.total_positive,
                "interviews": m.total_interviews,
                "offers":     m.total_offers,
                "reply_rate":     m.reply_rate,
                "positive_rate":  m.positive_rate,
                "interview_rate": m.interview_rate,
            },
            "top_hooks":     m.top_hooks,
            "top_subjects":  m.top_subjects[:5],
            "patterns": [
                {
                    "feature": f"{p.feature_key}={p.feature_val}",
                    "reply_rate": p.reply_rate,
                    "lift":       p.lift,
                    "n":          p.send_count,
                    "significant": p.is_significant(),
                }
                for p in snapshot.patterns[:10]
            ],
            "recommendations": [
                {
                    "type":   r.type.value,
                    "action": r.action,
                    "impact": r.impact_estimate,
                }
                for r in snapshot.recommendations[:5]
            ],
        }

    # ── Snapshot persistence ───────────────────────────────────────────────────

    def save_snapshot(self, snapshot: LearningSnapshot) -> None:
        """Persist snapshot to SQLite for week-over-week comparison."""
        try:
            _LEARNING_DB.parent.mkdir(exist_ok=True)
            with sqlite3.connect(_LEARNING_DB) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS learning_snapshots (
                        id             INTEGER PRIMARY KEY AUTOINCREMENT,
                        snapshot_date  TEXT NOT NULL,
                        metrics_json   TEXT NOT NULL,
                        recs_json      TEXT NOT NULL,
                        markdown       TEXT,
                        created_at     INTEGER NOT NULL
                    )
                """)
                import dataclasses
                metrics_d = self._metrics_to_dict(snapshot.metrics)
                recs_d    = [
                    {"type": r.type.value, "action": r.action, "impact": r.impact_estimate}
                    for r in snapshot.recommendations
                ]
                conn.execute(
                    """INSERT INTO learning_snapshots
                       (snapshot_date, metrics_json, recs_json, markdown, created_at)
                       VALUES (?, ?, ?, ?, ?)""",
                    (
                        snapshot.snapshot_date,
                        json.dumps(metrics_d),
                        json.dumps(recs_d),
                        snapshot.digest_markdown,
                        int(time.time()),
                    )
                )
        except Exception as exc:
            log.warning("Save snapshot: %s", exc)

    def load_prior_snapshot(self) -> Optional[dict]:
        """Load previous snapshot for week-over-week comparison."""
        try:
            with sqlite3.connect(_LEARNING_DB) as conn:
                row = conn.execute(
                    "SELECT metrics_json FROM learning_snapshots ORDER BY created_at DESC LIMIT 1 OFFSET 1"
                ).fetchone()
                if row:
                    return json.loads(row[0])
        except Exception:
            pass
        return None

    # ── ASCII helpers ──────────────────────────────────────────────────────────

    @staticmethod
    def _funnel_chart(m: OutreachMetrics) -> str:
        stages = [
            ("Sent",       m.total_sent,       1.0),
            ("Delivered",  m.total_delivered,  m.delivery_rate),
            ("Replied",    m.total_replied,     m.reply_rate),
            ("Positive",   m.total_positive,    m.positive_rate),
            ("Interviews", m.total_interviews,  m.interview_rate),
        ]
        lines = []
        for label, count, rate in stages:
            if count == 0:
                continue
            bar = _bar(rate, max_val=1.0, width=12)
            lines.append(f"  {label:<12} {count:>4}  {bar}  {rate:.0%}")
        return "\n".join(lines)

    @staticmethod
    def _metrics_to_dict(m: OutreachMetrics) -> dict:
        return {
            "total_sent": m.total_sent,
            "total_replied": m.total_replied,
            "total_positive": m.total_positive,
            "total_interviews": m.total_interviews,
            "total_offers": m.total_offers,
        }


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _bar(rate: float, max_val: float = 1.0, width: int = _BAR_WIDTH) -> str:
    """ASCII progress bar for a rate (0-max_val) → 0-width chars."""
    filled = int((rate / max_val) * width) if max_val > 0 else 0
    filled = max(0, min(width, filled))
    return "█" * filled + "░" * (width - filled)
