from __future__ import annotations

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict


class QueryToken(BaseModel):
    """A discrete requirement or pain point clause (Query Q_i)."""
    id: str = Field(..., description="Unique query identifier, e.g. q_0")
    text: str = Field(..., description="Extracted job requirement clause")
    category: str = Field(default="general", description="tech, scale, impact, seniority, general")
    weight: float = Field(default=1.0, description="Query importance weight")


class KeyToken(BaseModel):
    """A discrete candidate capability or experience identifier (Key K_j)."""
    id: str = Field(..., description="Unique key identifier, e.g. k_0")
    text: str = Field(..., description="Candidate skill or experience bullet headline")
    category: str = Field(default="general", description="tech, scale, impact, seniority, general")
    source: str = Field(default="profile", description="resume, profile, github, project")


class ValuePayload(BaseModel):
    """The actionable proof point and concrete metric payload (Value V_j)."""
    id: str = Field(..., description="Unique value identifier corresponding to k_j")
    proof_point: str = Field(..., description="Quantifiable metric, STAR story, or achievement")
    context: str = Field(default="", description="Project or company where achieved")
    impact_metric: Optional[str] = Field(None, description="e.g. '<50ms latency', '100k DAU'")


class AttentionHeadResult(BaseModel):
    """Attention calculation output for a single attention head."""
    head_name: str  # tech_stack, scale_systems, business_impact, seniority_leadership
    head_score: float = Field(..., ge=0.0, le=100.0, description="Head alignment score (0-100)")
    top_matches: List[Dict[str, Any]] = Field(default_factory=list, description="Top Q_i -> K_j attended pairs")


class AttentionMatrix(BaseModel):
    """Full NxM attention weight matrix alpha_ij."""
    query_tokens: List[QueryToken]
    key_tokens: List[KeyToken]
    weights: List[List[float]] = Field(..., description="N_queries x N_keys attention weights summing to 1.0 per row")


class TailoredBullet(BaseModel):
    """Synthesized resume bullet based on attention weights."""
    original_text: str
    tailored_text: str
    attention_score: float
    matched_queries: List[str]
    quant_metric: Optional[str] = None


class CrossAttentionOutreachHook(BaseModel):
    """Personalized cold outreach hook generated by cross-attending contact pain points."""
    target_pain_point: str
    candidate_proof_point: str
    attention_weight: float
    hook_sentence: str
    call_to_action: str


class MultiHeadAttentionResult(BaseModel):
    """Complete output of the Transformer Multi-Head Q,K,V Attention Engine."""
    overall_score: float = Field(..., ge=0.0, le=100.0, description="Overall Q,K,V alignment score (0-100)")
    fit_label: str
    heads: Dict[str, AttentionHeadResult]
    matrix: AttentionMatrix
    top_attended_values: List[ValuePayload]
    tailored_bullets: List[TailoredBullet]
    outreach_hooks: List[CrossAttentionOutreachHook]
    summary_insight: str
