import React, { useState, useEffect } from 'react';
import {
  Box,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Grid,
  Chip,
  Paper,
  Stack,
  CircularProgress,
} from '@mui/material';
import {
  Assessment as ReportIcon,
  ContentCopy as CopyIcon,
  Download as DownloadIcon,
  Check as CheckIcon,
} from '@mui/icons-material';

import api from '../../api/axios';

interface LaborMarketReportData {
  status: string;
  generated_at: string;
  target_sector: string;
  macro_trends: {
    title: string;
    executive_summary: string;
    macro_metrics: Array<{ metric: string; value: string; trend: string; color: string }>;
    top_hiring_sectors: Array<{
      sector: string;
      hiring_status: string;
      salary_range_lpa: string;
      key_tech_stack: string[];
    }>;
  };
  ranked_target_companies: Array<{
    name: string;
    domain: string;
    tier: string;
    signal_score: number;
    funding_stage: string;
    hiring_signals: string;
  }>;
  abm_playbook_rules: string[];
}

interface LaborMarketReportModalProps {
  open: boolean;
  onClose: () => void;
}

export const LaborMarketReportModal: React.FC<LaborMarketReportModalProps> = ({ open, onClose }) => {
  const [data, setData] = useState<LaborMarketReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (open) {
      setLoading(true);
      api.get<LaborMarketReportData>('/api/reports/labor-market-intelligence')
        .then((res) => setData(res.data))
        .catch((err) => console.error('Failed to load report:', err))
        .finally(() => setLoading(false));
    }
  }, [open]);

  const generateMarkdown = () => {
    if (!data) return '';
    return `# 📊 ${data.macro_trends.title}
*Generated by Job Finder Intelligence Engine — ${new Date(data.generated_at).toLocaleDateString()}*

## ⚡ Executive Summary
${data.macro_trends.executive_summary}

## 📈 Macro Hiring Metrics
${data.macro_trends.macro_metrics.map((m) => `- **${m.metric}**: ${m.value} (${m.trend})`).join('\n')}

## 🏢 Top Hiring Sectors
${data.macro_trends.top_hiring_sectors.map((s) => `### ${s.sector}
- Status: ${s.hiring_status}
- Typical Compensation: ${s.salary_range_lpa}
- Core Stack: ${s.key_tech_stack.join(', ')}`).join('\n\n')}

## 🎯 Top Ranked Target Companies & Signals
${data.ranked_target_companies.map((c) => `- **${c.name}** (${c.tier} | Signal Score: ${c.signal_score}%): ${c.hiring_signals}`).join('\n')}

## 🚀 Account-Based Outreach Playbook
${data.abm_playbook_rules.join('\n')}
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handleDownload = () => {
    const blob = new Blob([generateMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Labor_Market_Report_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: {
          bgcolor: '#0D131F',
          border: '1.5px solid rgba(0, 240, 255, 0.3)',
          borderRadius: '20px',
          color: '#F8FAFC',
        },
      }}
    >
      <DialogTitle sx={{ p: 3, borderBottom: '1px solid rgba(255, 255, 255, 0.1)' }}>
        <Stack direction="row" justifyContent="space-between" alignItems="center">
          <Stack direction="row" spacing={1.5} alignItems="center">
            <ReportIcon sx={{ color: '#00FFA3', fontSize: 28 }} />
            <Box>
              <Typography variant="h6" sx={{ fontWeight: 900, color: '#F8FAFC' }}>
                Labor Market Intelligence & Hiring Signals Report
              </Typography>
              <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                Real-time GCC expansion, FinTech demand, and Account-Based Conversion Data
              </Typography>
            </Box>
          </Stack>

          <Stack direction="row" spacing={1}>
            <Button
              size="small"
              variant="outlined"
              startIcon={copied ? <CheckIcon /> : <CopyIcon />}
              onClick={handleCopy}
              sx={{ color: '#00F0FF', borderColor: '#00F0FF', textTransform: 'none', fontWeight: 800 }}
            >
              {copied ? 'Copied' : 'Copy Report'}
            </Button>
            <Button
              size="small"
              variant="contained"
              startIcon={<DownloadIcon />}
              onClick={handleDownload}
              sx={{ bgcolor: '#00FFA3', color: '#06090E', fontWeight: 900, textTransform: 'none' }}
            >
              Download .md
            </Button>
          </Stack>
        </Stack>
      </DialogTitle>

      <DialogContent sx={{ p: 3 }}>
        {loading ? (
          <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
            <CircularProgress sx={{ color: '#00FFA3' }} />
          </Box>
        ) : data ? (
          <Stack spacing={3}>
            {/* Executive Summary */}
            <Paper sx={{ p: 2.5, bgcolor: '#06090E', border: '1px solid rgba(0, 255, 163, 0.25)', borderRadius: '12px' }}>
              <Typography variant="subtitle2" sx={{ color: '#00FFA3', fontWeight: 900, mb: 1, textTransform: 'uppercase' }}>
                ⚡ Executive Summary
              </Typography>
              <Typography variant="body2" sx={{ color: '#E2E8F0', lineHeight: 1.6 }}>
                {data.macro_trends.executive_summary}
              </Typography>
            </Paper>

            {/* Macro Metrics */}
            <Grid container spacing={2}>
              {data.macro_trends.macro_metrics.map((m) => (
                <Grid key={m.metric} size={{ xs: 6, sm: 3 }}>
                  <Box sx={{ p: 2, bgcolor: '#06090E', borderRadius: '12px', border: `1px solid ${m.color}40` }}>
                    <Typography variant="caption" sx={{ color: '#94A3B8', fontWeight: 700, display: 'block', mb: 0.5 }}>
                      {m.metric}
                    </Typography>
                    <Typography variant="h6" sx={{ fontWeight: 900, color: m.color }}>
                      {m.value}
                    </Typography>
                    <Chip label={m.trend} size="small" sx={{ bgcolor: `${m.color}20`, color: m.color, fontWeight: 800, height: 20, fontSize: '0.65rem', mt: 0.5 }} />
                  </Box>
                </Grid>
              ))}
            </Grid>

            {/* Target Companies */}
            <Box>
              <Typography variant="subtitle1" sx={{ fontWeight: 900, color: '#00F0FF', mb: 1.5 }}>
                🏢 High-Yield Target Companies & Live Signals
              </Typography>
              <Grid container spacing={1.5}>
                {data.ranked_target_companies.map((c) => (
                  <Grid key={c.name} size={{ xs: 12, sm: 6 }}>
                    <Paper sx={{ p: 2, bgcolor: '#06090E', borderRadius: '12px', border: '1px solid rgba(255, 255, 255, 0.08)' }}>
                      <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 1 }}>
                        <Typography variant="subtitle2" sx={{ fontWeight: 900, color: '#F8FAFC' }}>
                          {c.name}
                        </Typography>
                        <Chip label={`${c.signal_score}% Fit`} size="small" sx={{ bgcolor: 'rgba(0, 255, 163, 0.15)', color: '#00FFA3', fontWeight: 800, height: 22 }} />
                      </Stack>
                      <Typography variant="caption" sx={{ color: '#94A3B8', display: 'block', mb: 0.5 }}>
                        {c.tier} • {c.funding_stage}
                      </Typography>
                      <Typography variant="body2" sx={{ color: '#CBD5E1', fontSize: '0.8rem' }}>
                        {c.hiring_signals}
                      </Typography>
                    </Paper>
                  </Grid>
                ))}
              </Grid>
            </Box>

            {/* ABM Playbook */}
            <Paper sx={{ p: 2.5, bgcolor: '#06090E', border: '1px solid rgba(255, 230, 0, 0.25)', borderRadius: '12px' }}>
              <Typography variant="subtitle2" sx={{ color: '#FFE600', fontWeight: 900, mb: 1.5, textTransform: 'uppercase' }}>
                🎯 Account-Based Outreach Playbook
              </Typography>
              <Stack spacing={1}>
                {data.abm_playbook_rules.map((rule, idx) => (
                  <Typography key={idx} variant="body2" sx={{ color: '#E2E8F0', fontSize: '0.85rem' }}>
                    {rule}
                  </Typography>
                ))}
              </Stack>
            </Paper>
          </Stack>
        ) : null}
      </DialogContent>

      <DialogActions sx={{ p: 2.5, borderTop: '1px solid rgba(255, 255, 255, 0.1)' }}>
        <Button onClick={onClose} sx={{ color: '#94A3B8', textTransform: 'none', fontWeight: 700 }}>
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};
