"""initial schema

Revision ID: b4686927ddeb
Revises: 
Create Date: 2026-07-30 18:09:56.337107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4686927ddeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_records', 'reply_sentiment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('outreach_records', 'timezone_detected',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_records', 'timezone_detected',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('outreach_records', 'reply_sentiment',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
