"""
tracker.py — Human-readable application tracker backed by the SQLite DB.

Usage:
    # Regenerate data/applications.md from DB
    python -m src.tracker

    # Update a specific row's status (writes back to DB + regenerates)
    python -m src.tracker --update 42 Interview

Canonical statuses:
    Ready       → AI analysis done, not yet actioned
    Outreach    → Cold email sent via NEXUS
    Applied     → Manually applied
    Replied     → Got a reply from company
    Interview   → In interview process
    Offer       → Offer received
    Rejected    → Rejected by company
    Skip        → Below threshold / you chose to skip
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from sqlalchemy import case, func
from sqlalchemy.orm import Session

from src.database import SessionLocal
from src.models import Application, Job, OutreachRecord

TRACKER_PATH = Path(__file__).parent.parent / "data" / "applications.md"

# Ordered for display in the status legend
CANONICAL_STATUSES = [
    "Ready",
    "Outreach",
    "Applied",
    "Replied",
    "Interview",
    "Offer",
    "Rejected",
    "Skip",
]

# Map DB application.status values → display status
_DB_STATUS_MAP = {
    "pending":   "Ready",
    "ready":     "Ready",
    "applied":   "Applied",
    "interview": "Interview",
    "offer":     "Offer",
    "rejected":  "Rejected",
    "skip":      "Skip",
    "skipped":   "Skip",
}

# Map display status back → DB value
_DISPLAY_TO_DB = {
    "Ready":     "ready",
    "Outreach":  "ready",   # outreach is tracked via OutreachRecord
    "Applied":   "applied",
    "Replied":   "applied",
    "Interview": "interview",
    "Offer":     "offer",
    "Rejected":  "rejected",
    "Skip":      "skip",
}


# ---------------------------------------------------------------------------
# Status resolution
# ---------------------------------------------------------------------------

def _resolve_status(app: Application, has_outreach: bool, has_reply: bool) -> str:
    """Determine display status from DB fields + outreach records."""
    db_status = (app.status or "pending").lower()

    if db_status in ("interview", "offer", "rejected", "skip", "skipped", "applied"):
        return _DB_STATUS_MAP[db_status]

    # For 'pending'/'ready' rows, check if outreach went out
    if has_reply:
        return "Replied"
    if has_outreach:
        return "Outreach"

    return "Ready"


# ---------------------------------------------------------------------------
# Fetch rows from DB
# ---------------------------------------------------------------------------

def _fetch_rows(db: Session) -> list[dict]:
    """
    Join jobs → applications → outreach_records and return dicts ready
    for table rendering.
    """
    # Subquery: did this job get any outreach sent?
    outreach_sub = (
        db.query(
            OutreachRecord.job_id,
            func.count(OutreachRecord.id).label("outreach_count"),
            func.max(
                case(
                    (OutreachRecord.status == "replied", 1),
                    else_=0
                )
            ).label("has_reply"),
        )
        .filter(OutreachRecord.email_sent == True)
        .group_by(OutreachRecord.job_id)
        .subquery()
    )

    rows = (
        db.query(Job, Application, outreach_sub.c.outreach_count, outreach_sub.c.has_reply)
        .join(Application, Application.job_id == Job.id)
        .outerjoin(outreach_sub, outreach_sub.c.job_id == Job.id)
        .order_by(Application.created_at.desc())
        .all()
    )

    results = []
    for i, (job, app, outreach_count, has_reply) in enumerate(rows, start=1):
        status = _resolve_status(
            app,
            has_outreach=bool(outreach_count and outreach_count > 0),
            has_reply=bool(has_reply),
        )
        results.append({
            "num": i,
            "app_id": app.id,
            "date": (app.created_at or datetime.utcnow()).strftime("%Y-%m-%d"),
            "company": job.company or "—",
            "role": job.title or "—",
            "score": f"{app.match_score:.0f}%" if app.match_score is not None else "—",
            "status": status,
            "url": job.url or "",
            "outreach": outreach_count or 0,
            "notes": "",
        })

    return results


# ---------------------------------------------------------------------------
# Render markdown
# ---------------------------------------------------------------------------

def _render(rows: list[dict]) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    header = f"""\
# Application Tracker

> Auto-generated by NEXUS — last updated **{now}**
> Edit statuses via: `python -m src.tracker --update <app_id> <Status>`
>
> **Statuses:** {" · ".join(CANONICAL_STATUSES)}

"""

    if not rows:
        return header + "_No applications yet. Run the pipeline to populate._\n"

    # Count by status for summary
    from collections import Counter
    counts = Counter(r["status"] for r in rows)
    summary_parts = [f"{s}: **{counts[s]}**" for s in CANONICAL_STATUSES if counts[s]]
    header += "**Summary:** " + " | ".join(summary_parts) + "\n\n"

    # Table
    col_w = {
        "num": 3,
        "date": 10,
        "company": max(len(r["company"]) for r in rows),
        "role": max(len(r["role"]) for r in rows),
        "score": 6,
        "status": max(len(r["status"]) for r in rows),
        "outreach": 8,
    }
    # Enforce minimums
    col_w["company"] = max(col_w["company"], 7)
    col_w["role"] = max(col_w["role"], 4)
    col_w["status"] = max(col_w["status"], 6)

    def cell(val, w):
        return str(val).ljust(w)

    def row_line(r):
        url = r["url"]
        role_cell = f"[{r['role']}]({url})" if url else r["role"]
        # pad role cell to account for markdown link syntax hiding
        role_display = r["role"].ljust(col_w["role"])
        if url:
            role_cell = f"[{role_display.rstrip()}]({url})"
        else:
            role_cell = role_display

        return (
            f"| {cell(r['num'], col_w['num'])} "
            f"| {cell(r['date'], col_w['date'])} "
            f"| {cell(r['company'], col_w['company'])} "
            f"| {role_cell} "
            f"| {cell(r['score'], col_w['score'])} "
            f"| {cell(r['status'], col_w['status'])} "
            f"| {cell(r['outreach'], col_w['outreach'])} "
            f"| {r['app_id']} "
            f"|"
        )

    sep = (
        f"| {'-' * col_w['num']} "
        f"| {'-' * col_w['date']} "
        f"| {'-' * col_w['company']} "
        f"| {'-' * col_w['role']} "
        f"| {'-' * col_w['score']} "
        f"| {'-' * col_w['status']} "
        f"| {'-' * col_w['outreach']} "
        f"| --- "
        f"|"
    )

    thead = (
        f"| {'#'.ljust(col_w['num'])} "
        f"| {'Date'.ljust(col_w['date'])} "
        f"| {'Company'.ljust(col_w['company'])} "
        f"| {'Role'.ljust(col_w['role'])} "
        f"| {'Score'.ljust(col_w['score'])} "
        f"| {'Status'.ljust(col_w['status'])} "
        f"| {'Outreach'.ljust(col_w['outreach'])} "
        f"| App ID "
        f"|"
    )

    lines = [thead, sep] + [row_line(r) for r in rows]
    return header + "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Write tracker
# ---------------------------------------------------------------------------

def generate(db: Optional[Session] = None) -> str:
    """Generate tracker markdown. Returns the rendered string."""
    own_session = db is None
    if own_session:
        db = SessionLocal()
    try:
        rows = _fetch_rows(db)
        content = _render(rows)
        TRACKER_PATH.parent.mkdir(parents=True, exist_ok=True)
        TRACKER_PATH.write_text(content, encoding="utf-8")
        return content
    finally:
        if own_session:
            db.close()


# ---------------------------------------------------------------------------
# Update a row's status
# ---------------------------------------------------------------------------

def update_status(app_id: int, new_status: str, db: Optional[Session] = None) -> None:
    """Write new_status into the DB for the given application ID."""
    if new_status not in CANONICAL_STATUSES:
        raise ValueError(
            f"Unknown status '{new_status}'. Choose from: {', '.join(CANONICAL_STATUSES)}"
        )

    own_session = db is None
    if own_session:
        db = SessionLocal()
    try:
        app = db.query(Application).filter(Application.id == app_id).first()
        if not app:
            raise ValueError(f"No application with id={app_id}")
        app.status = _DISPLAY_TO_DB[new_status]
        app.updated_at = datetime.utcnow()
        db.commit()
        print(f"✅ Application {app_id} → {new_status}")
    finally:
        if own_session:
            db.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli():
    parser = argparse.ArgumentParser(
        description="NEXUS Application Tracker — generate or update data/applications.md"
    )
    parser.add_argument(
        "--update",
        nargs=2,
        metavar=("APP_ID", "STATUS"),
        help="Update an application's status. Example: --update 42 Interview",
    )
    args = parser.parse_args()

    if args.update:
        app_id_str, status = args.update
        try:
            app_id = int(app_id_str)
        except ValueError:
            print(f"❌ APP_ID must be an integer, got: {app_id_str}", file=sys.stderr)
            sys.exit(1)
        try:
            update_status(app_id, status)
        except ValueError as e:
            print(f"❌ {e}", file=sys.stderr)
            sys.exit(1)

    content = generate()
    row_count = content.count("\n| ") - 2  # subtract header + sep
    print(f"✅ Tracker written → {TRACKER_PATH}  ({max(row_count, 0)} applications)")


if __name__ == "__main__":
    _cli()
